package br.gov.pb.paraiba.model;

// default package
// Generated 17/11/2009 11:35:41 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Distribuicao generated by hbm2java
 */
@Entity
@Table(name = "distribuicao", catalog = "sgbo")
public class Distribuicao implements java.io.Serializable {

	private Integer idDistribuicao;
	private Registro registro;
	private Medico medico;
	private Estabelecimento estabelecimento;
	private Date dataLiberacao;
	private Date horaLiberacao;
	private Date dataSaida;
	private Date horaSaida;
	private String nomeReceptor;
	private String rgctReceptor;
	private Character sexoReceptor;
	private String nomePortador;
	private String rgPortador;
	private String vinculoPortador;
	private String motivoSaida;
	private Set<Reingresso> reingressosForMedicoDevolveu = new HashSet<Reingresso>(
			0);
	private Set<Reingresso> reingressosForNumero = new HashSet<Reingresso>(0);

	public Distribuicao() {
	}

	public Distribuicao(Registro registro, String nomePortador,
			String rgPortador, String motivoSaida) {
		this.registro = registro;
		this.nomePortador = nomePortador;
		this.rgPortador = rgPortador;
		this.motivoSaida = motivoSaida;
	}

	public Distribuicao(Registro registro, Medico medico,
			Estabelecimento estabelecimento, Date dataLiberacao,
			Date horaLiberacao, Date dataSaida, Date horaSaida,
			String nomeReceptor, String rgctReceptor, Character sexoReceptor,
			String nomePortador, String rgPortador, String vinculoPortador,
			String motivoSaida, Set<Reingresso> reingressosForMedicoDevolveu,
			Set<Reingresso> reingressosForNumero) {
		this.registro = registro;
		this.medico = medico;
		this.estabelecimento = estabelecimento;
		this.dataLiberacao = dataLiberacao;
		this.horaLiberacao = horaLiberacao;
		this.dataSaida = dataSaida;
		this.horaSaida = horaSaida;
		this.nomeReceptor = nomeReceptor;
		this.rgctReceptor = rgctReceptor;
		this.sexoReceptor = sexoReceptor;
		this.nomePortador = nomePortador;
		this.rgPortador = rgPortador;
		this.vinculoPortador = vinculoPortador;
		this.motivoSaida = motivoSaida;
		this.reingressosForMedicoDevolveu = reingressosForMedicoDevolveu;
		this.reingressosForNumero = reingressosForNumero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDistribuicao", unique = true, nullable = false)
	public Integer getIdDistribuicao() {
		return this.idDistribuicao;
	}

	public void setIdDistribuicao(Integer idDistribuicao) {
		this.idDistribuicao = idDistribuicao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numero", nullable = false)
	public Registro getRegistro() {
		return this.registro;
	}

	public void setRegistro(Registro registro) {
		this.registro = registro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transplantador")
	public Medico getMedico() {
		return this.medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "localCirurgia")
	public Estabelecimento getEstabelecimento() {
		return this.estabelecimento;
	}

	public void setEstabelecimento(Estabelecimento estabelecimento) {
		this.estabelecimento = estabelecimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataLiberacao", length = 10)
	public Date getDataLiberacao() {
		return this.dataLiberacao;
	}

	public void setDataLiberacao(Date dataLiberacao) {
		this.dataLiberacao = dataLiberacao;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaLiberacao", length = 8)
	public Date getHoraLiberacao() {
		return this.horaLiberacao;
	}

	public void setHoraLiberacao(Date horaLiberacao) {
		this.horaLiberacao = horaLiberacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataSaida", length = 10)
	public Date getDataSaida() {
		return this.dataSaida;
	}

	public void setDataSaida(Date dataSaida) {
		this.dataSaida = dataSaida;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaSaida", length = 8)
	public Date getHoraSaida() {
		return this.horaSaida;
	}

	public void setHoraSaida(Date horaSaida) {
		this.horaSaida = horaSaida;
	}

	@Column(name = "nomeReceptor", length = 50)
	public String getNomeReceptor() {
		return this.nomeReceptor;
	}

	public void setNomeReceptor(String nomeReceptor) {
		this.nomeReceptor = nomeReceptor;
	}

	@Column(name = "rgctReceptor", length = 45)
	public String getRgctReceptor() {
		return this.rgctReceptor;
	}

	public void setRgctReceptor(String rgctReceptor) {
		this.rgctReceptor = rgctReceptor;
	}

	@Column(name = "sexoReceptor", length = 1)
	public Character getSexoReceptor() {
		return this.sexoReceptor;
	}

	public void setSexoReceptor(Character sexoReceptor) {
		this.sexoReceptor = sexoReceptor;
	}

	@Column(name = "nomePortador", nullable = false, length = 50)
	public String getNomePortador() {
		return this.nomePortador;
	}

	public void setNomePortador(String nomePortador) {
		this.nomePortador = nomePortador;
	}

	@Column(name = "rgPortador", nullable = false, length = 8)
	public String getRgPortador() {
		return this.rgPortador;
	}

	public void setRgPortador(String rgPortador) {
		this.rgPortador = rgPortador;
	}

	@Column(name = "vinculoPortador", length = 45)
	public String getVinculoPortador() {
		return this.vinculoPortador;
	}

	public void setVinculoPortador(String vinculoPortador) {
		this.vinculoPortador = vinculoPortador;
	}

	@Column(name = "motivoSaida", nullable = false, length = 12)
	public String getMotivoSaida() {
		return this.motivoSaida;
	}

	public void setMotivoSaida(String motivoSaida) {
		this.motivoSaida = motivoSaida;
	}


}
