package br.gov.pb.paraiba.model;

// default package
// Generated 19/11/2009 16:03:54 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reingresso generated by hbm2java
 */
@Entity
@Table(name = "reingresso", catalog = "sgbo")
public class Reingresso implements java.io.Serializable {

	private Integer idReingresso;
	private Distribuicao distribuicaoByMedicoDevolveu;
	private Distribuicao distribuicaoByNumero;
	private Distribuicao distribuicaoByRgctRecusou;
	private Distribuicao distribuicaoByNomeRecusou;
	private Date dataReingresso;
	private Date horaReingresso;
	private String motivoDevolucao;
	private Date dataReavaliacao;
	private Date horaReavaliacao;
	private String resultadoReavaliacao;
	private String destinoTecido;

	public Reingresso() {
	}

	public Reingresso(Distribuicao distribuicaoByNumero,
			Distribuicao distribuicaoByRgctRecusou,
			Distribuicao distribuicaoByNomeRecusou) {
		this.distribuicaoByNumero = distribuicaoByNumero;
		this.distribuicaoByRgctRecusou = distribuicaoByRgctRecusou;
		this.distribuicaoByNomeRecusou = distribuicaoByNomeRecusou;
	}

	public Reingresso(Distribuicao distribuicaoByMedicoDevolveu,
			Distribuicao distribuicaoByNumero,
			Distribuicao distribuicaoByRgctRecusou,
			Distribuicao distribuicaoByNomeRecusou, Date dataReingresso,
			Date horaReingresso, String motivoDevolucao, Date dataReavaliacao,
			Date horaReavaliacao, String resultadoReavaliacao,
			String destinoTecido) {
		this.distribuicaoByMedicoDevolveu = distribuicaoByMedicoDevolveu;
		this.distribuicaoByNumero = distribuicaoByNumero;
		this.distribuicaoByRgctRecusou = distribuicaoByRgctRecusou;
		this.distribuicaoByNomeRecusou = distribuicaoByNomeRecusou;
		this.dataReingresso = dataReingresso;
		this.horaReingresso = horaReingresso;
		this.motivoDevolucao = motivoDevolucao;
		this.dataReavaliacao = dataReavaliacao;
		this.horaReavaliacao = horaReavaliacao;
		this.resultadoReavaliacao = resultadoReavaliacao;
		this.destinoTecido = destinoTecido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idReingresso", unique = true, nullable = false)
	public Integer getIdReingresso() {
		return this.idReingresso;
	}

	public void setIdReingresso(Integer idReingresso) {
		this.idReingresso = idReingresso;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numero", nullable = false)
	public Distribuicao getDistribuicaoByNumero() {
		return this.distribuicaoByNumero;
	}

	public void setDistribuicaoByNumero(Distribuicao distribuicaoByNumero) {
		this.distribuicaoByNumero = distribuicaoByNumero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rgctRecusou", nullable = false)
	public Distribuicao getDistribuicaoByRgctRecusou() {
		return this.distribuicaoByRgctRecusou;
	}

	public void setDistribuicaoByRgctRecusou(
			Distribuicao distribuicaoByRgctRecusou) {
		this.distribuicaoByRgctRecusou = distribuicaoByRgctRecusou;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nomeRecusou", nullable = false)
	public Distribuicao getDistribuicaoByNomeRecusou() {
		return this.distribuicaoByNomeRecusou;
	}

	public void setDistribuicaoByNomeRecusou(
			Distribuicao distribuicaoByNomeRecusou) {
		this.distribuicaoByNomeRecusou = distribuicaoByNomeRecusou;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataReingresso", length = 10)
	public Date getDataReingresso() {
		return this.dataReingresso;
	}

	public void setDataReingresso(Date dataReingresso) {
		this.dataReingresso = dataReingresso;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaReingresso", length = 8)
	public Date getHoraReingresso() {
		return this.horaReingresso;
	}

	public void setHoraReingresso(Date horaReingresso) {
		this.horaReingresso = horaReingresso;
	}

	@Column(name = "motivoDevolucao", length = 45)
	public String getMotivoDevolucao() {
		return this.motivoDevolucao;
	}

	public void setMotivoDevolucao(String motivoDevolucao) {
		this.motivoDevolucao = motivoDevolucao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataReavaliacao", length = 10)
	public Date getDataReavaliacao() {
		return this.dataReavaliacao;
	}

	public void setDataReavaliacao(Date dataReavaliacao) {
		this.dataReavaliacao = dataReavaliacao;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaReavaliacao", length = 8)
	public Date getHoraReavaliacao() {
		return this.horaReavaliacao;
	}

	public void setHoraReavaliacao(Date horaReavaliacao) {
		this.horaReavaliacao = horaReavaliacao;
	}

	@Column(name = "resultadoReavaliacao", length = 45)
	public String getResultadoReavaliacao() {
		return this.resultadoReavaliacao;
	}

	public void setResultadoReavaliacao(String resultadoReavaliacao) {
		this.resultadoReavaliacao = resultadoReavaliacao;
	}

	@Column(name = "destinoTecido", length = 45)
	public String getDestinoTecido() {
		return this.destinoTecido;
	}

	public void setDestinoTecido(String destinoTecido) {
		this.destinoTecido = destinoTecido;
	}

}
