package br.gov.pb.paraiba.model;

// default package
// Generated 19/11/2009 16:03:54 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estabelecimento generated by hbm2java
 */
@Entity
@Table(name = "estabelecimento", catalog = "sgbo")
public class Estabelecimento implements java.io.Serializable {

	private Integer idEstabelecimento;
	private String nome;
	private String endereco;
	private String telefone;
	private Set<Distribuicao> distribuicoes = new HashSet<Distribuicao>(0);
	private Set<Registro> registrosForLocalCaptacao = new HashSet<Registro>(0);
	private Set<Registro> registrosForLocalObitoDoador = new HashSet<Registro>(
			0);

	public Estabelecimento() {
	}

	public Estabelecimento(String nome) {
		this.nome = nome;
	}

	public Estabelecimento(String nome, String endereco, String telefone,
			Set<Distribuicao> distribuicaos,
			Set<Registro> registrosForLocalCaptacao,
			Set<Registro> registrosForLocalObitoDoador) {
		this.nome = nome;
		this.endereco = endereco;
		this.telefone = telefone;
		this.distribuicoes = distribuicoes;
		this.registrosForLocalCaptacao = registrosForLocalCaptacao;
		this.registrosForLocalObitoDoador = registrosForLocalObitoDoador;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEstabelecimento", unique = true, nullable = false)
	public Integer getIdEstabelecimento() {
		return this.idEstabelecimento;
	}

	public void setIdEstabelecimento(Integer idEstabelecimento) {
		this.idEstabelecimento = idEstabelecimento;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", length = 100)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "telefone", length = 9)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}


}
