package br.gov.pb.paraiba.model;

// default package
// Generated 17/11/2009 12:58:54 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "registro", catalog = "sgbo")
public class Registro implements java.io.Serializable {

	private Integer idRegistro;
	private String numero;
	private String nomeDoador;
	private Integer idadeDoador;
	private Character sexo;
	private Integer causaMorteDoador;
	private Integer localObitoDoador;
	private Date dataObito;
	private Date horaObito;
	private Integer localCaptacao;
	private Date dataCaptacao;
	private Date horaCaptacao;
	private Date dataEntreda;
	private Date horaEntrada;
	private String sorologia;
	private boolean preservada;
	private Date dataPreservacao;
	private Date horaPreservacao;
	private Date dataPreservacaoFinal;
	private Date horaPreservacaoFinal;
	private String resultadoAvaliacao;
	private Date validade;
	private Boolean aih;
	private String procedimento;

	public Registro() {
	}

	public Registro(String numero, boolean preservada, Date validade) {
		this.numero = numero;
		this.preservada = preservada;
		this.validade = validade;
	}

	public Registro(String numero, String nomeDoador, Integer idadeDoador,
			Character sexo, Integer causaMorteDoador, Integer localObitoDoador,
			Date dataObito, Date horaObito, Integer localCaptacao,
			Date dataCaptacao, Date horaCaptacao, Date dataEntreda,
			Date horaEntrada, String sorologia, boolean preservada,
			Date dataPreservacao, Date horaPreservacao,
			Date dataPreservacaoFinal, Date horaPreservacaoFinal,
			String resultadoAvaliacao, Date validade, Boolean aih,
			String procedimento) {
		this.numero = numero;
		this.nomeDoador = nomeDoador;
		this.idadeDoador = idadeDoador;
		this.sexo = sexo;
		this.causaMorteDoador = causaMorteDoador;
		this.localObitoDoador = localObitoDoador;
		this.dataObito = dataObito;
		this.horaObito = horaObito;
		this.localCaptacao = localCaptacao;
		this.dataCaptacao = dataCaptacao;
		this.horaCaptacao = horaCaptacao;
		this.dataEntreda = dataEntreda;
		this.horaEntrada = horaEntrada;
		this.sorologia = sorologia;
		this.preservada = preservada;
		this.dataPreservacao = dataPreservacao;
		this.horaPreservacao = horaPreservacao;
		this.dataPreservacaoFinal = dataPreservacaoFinal;
		this.horaPreservacaoFinal = horaPreservacaoFinal;
		this.resultadoAvaliacao = resultadoAvaliacao;
		this.validade = validade;
		this.aih = aih;
		this.procedimento = procedimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRegistro", unique = true, nullable = false)
	public Integer getIdRegistro() {
		return this.idRegistro;
	}

	public void setIdRegistro(Integer idRegistro) {
		this.idRegistro = idRegistro;
	}

	@Column(name = "numero", nullable = false, length = 16)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "nomeDoador", length = 50)
	public String getNomeDoador() {
		return this.nomeDoador;
	}

	public void setNomeDoador(String nomeDoador) {
		this.nomeDoador = nomeDoador;
	}

	@Column(name = "idadeDoador")
	public Integer getIdadeDoador() {
		return this.idadeDoador;
	}

	public void setIdadeDoador(Integer idadeDoador) {
		this.idadeDoador = idadeDoador;
	}

	@Column(name = "sexo", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	@Column(name = "causaMorteDoador")
	public Integer getCausaMorteDoador() {
		return this.causaMorteDoador;
	}

	public void setCausaMorteDoador(Integer causaMorteDoador) {
		this.causaMorteDoador = causaMorteDoador;
	}

	@Column(name = "localObitoDoador")
	public Integer getLocalObitoDoador() {
		return this.localObitoDoador;
	}

	public void setLocalObitoDoador(Integer localObitoDoador) {
		this.localObitoDoador = localObitoDoador;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataObito", length = 10)
	public Date getDataObito() {
		return this.dataObito;
	}

	public void setDataObito(Date dataObito) {
		this.dataObito = dataObito;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaObito", length = 8)
	public Date getHoraObito() {
		return this.horaObito;
	}

	public void setHoraObito(Date horaObito) {
		this.horaObito = horaObito;
	}

	@Column(name = "localCaptacao")
	public Integer getLocalCaptacao() {
		return this.localCaptacao;
	}

	public void setLocalCaptacao(Integer localCaptacao) {
		this.localCaptacao = localCaptacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataCaptacao", length = 10)
	public Date getDataCaptacao() {
		return this.dataCaptacao;
	}

	public void setDataCaptacao(Date dataCaptacao) {
		this.dataCaptacao = dataCaptacao;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaCaptacao", length = 8)
	public Date getHoraCaptacao() {
		return this.horaCaptacao;
	}

	public void setHoraCaptacao(Date horaCaptacao) {
		this.horaCaptacao = horaCaptacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataEntreda", length = 10)
	public Date getDataEntreda() {
		return this.dataEntreda;
	}

	public void setDataEntreda(Date dataEntreda) {
		this.dataEntreda = dataEntreda;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaEntrada", length = 8)
	public Date getHoraEntrada() {
		return this.horaEntrada;
	}

	public void setHoraEntrada(Date horaEntrada) {
		this.horaEntrada = horaEntrada;
	}

	@Column(name = "sorologia", length = 45)
	public String getSorologia() {
		return this.sorologia;
	}

	public void setSorologia(String sorologia) {
		this.sorologia = sorologia;
	}

	@Column(name = "preservada", nullable = false)
	public boolean isPreservada() {
		return this.preservada;
	}

	public void setPreservada(boolean preservada) {
		this.preservada = preservada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataPreservacao", length = 10)
	public Date getDataPreservacao() {
		return this.dataPreservacao;
	}

	public void setDataPreservacao(Date dataPreservacao) {
		this.dataPreservacao = dataPreservacao;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaPreservacao", length = 8)
	public Date getHoraPreservacao() {
		return this.horaPreservacao;
	}

	public void setHoraPreservacao(Date horaPreservacao) {
		this.horaPreservacao = horaPreservacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataPreservacaoFinal", length = 10)
	public Date getDataPreservacaoFinal() {
		return this.dataPreservacaoFinal;
	}

	public void setDataPreservacaoFinal(Date dataPreservacaoFinal) {
		this.dataPreservacaoFinal = dataPreservacaoFinal;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaPreservacaoFinal", length = 8)
	public Date getHoraPreservacaoFinal() {
		return this.horaPreservacaoFinal;
	}

	public void setHoraPreservacaoFinal(Date horaPreservacaoFinal) {
		this.horaPreservacaoFinal = horaPreservacaoFinal;
	}

	@Column(name = "resultadoAvaliacao", length = 45)
	public String getResultadoAvaliacao() {
		return this.resultadoAvaliacao;
	}

	public void setResultadoAvaliacao(String resultadoAvaliacao) {
		this.resultadoAvaliacao = resultadoAvaliacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "validade", nullable = false, length = 10)
	public Date getValidade() {
		return this.validade;
	}

	public void setValidade(Date validade) {
		this.validade = validade;
	}

	@Column(name = "aih")
	public Boolean getAih() {
		return this.aih;
	}

	public void setAih(Boolean aih) {
		this.aih = aih;
	}

	@Column(name = "procedimento", length = 16777215)
	public String getProcedimento() {
		return this.procedimento;
	}

	public void setProcedimento(String procedimento) {
		this.procedimento = procedimento;
	}

}
